version: 2

models:
  - name: stg_deal_changes
    description: "Cleaned deal change events from raw Pipedrive data (rename + type cast, no business logic)."
    columns:
      - name: deal_change_sk
        tests:
          - unique
          - not_null
      - name: deal_id
        tests: [not_null]
      - name: change_timestamp
        tests: [not_null]
      - name: changed_field_key
        tests: [not_null]

  - name: stg_stages
    description: "Cleaned stages dimension from raw Pipedrive stages table."
    columns:
      - name: stage_id
        tests: [not_null, unique]
      - name: stage_name
        tests: [not_null]

  - name: stg_activity
    description: "Cleaned activities from raw Pipedrive activity table (rename + type cast)."
    columns:
      - name: activity_sk
        tests:
          - unique
          - not_null
      - name: activity_id
        tests: [not_null]
      - name: deal_id
        description: "Associated deal identifier (nullable if activity is not linked to a deal)."
      - name: activity_type
        tests: [not_null]
      - name: assigned_user_id
        description: "User responsible for the activity (nullable if not assigned)."


  - name: stg_activity_types
    description: "Cleaned activity types lookup table (human-readable activity type names + active flag)."
    columns:
      - name: activity_type_id
        tests: [not_null, unique]
      - name: activity_type_name
        tests: [not_null]
      - name: is_active
        tests: [not_null]

  - name: stg_users
    description: "Cleaned users lookup table (basic user attributes for future joins)."
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: user_name
        tests: [not_null]

  - name: stg_fields
    description: "Cleaned metadata fields table (kept as-is for potential future enrichment/use)."
    columns:
      - name: field_id
        tests: [not_null, unique]
      - name: field_key
        tests: [not_null]
      - name: field_name
        tests: [not_null]
